### ISSUE TITLE
[meta] India UI MVP

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/quartz-frontend#463]
![Image](https://github.com/openclimatefix/nowcasting/assets/34686298/ffc023a0-cc33-4fdb-817a-f24ad91e2673)

Setup
- [x] Setup folder structure 
- [x] Setup mono repo build
- [x] Setup mono repo deploy on vercel
- [x] Page structure (no map), Side bar(info cards) + charts ------ layout -------
- [ ] Global state
- [ ] Auth

Data (BE FE)
- [ ] Data types
- [ ] Data formating
- [x] Data hook up

FE
- [ ] Info boxes
- [ ] Charts
- [ ] Toggles
- [ ] Tooltips 
- [ ] Icons

Things to do later
- [ ] add domain
